# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UC0rzL6js9LeqZIWnKyWHkqH-tManmsw
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')
df=pd.read_csv(r"C:\Users\suraj\Downloads\Real_Estate_Data_150.csv") #Load csv file
df

from sklearn.preprocessing import LabelEncoder  #Convert categorical labels into numerical integers

le_location=LabelEncoder()
le_aminities=LabelEncoder()

df['location_n']=le_location.fit_transform(df['Location'])
df['aminities_n']=le_aminities.fit_transform(df['Aminities'])
df

target=df['Total_Price']
target

df1=df.drop(['Total_Price','Location','Aminities'],axis='columns')
df1

target

df

from tkinter import ttk
import tkinter as tk
from tkinter import messagebox
import numpy as np
from sklearn import linear_model

# ------------------ MODEL ------------------
model = linear_model.LinearRegression()
model.fit(df1,target)

# ------------------ GUI ------------------
root = tk.Tk()
root.title("🏡 SmartProperty AI")
root.geometry("450x600")

# -------- Bedrooms --------
tk.Label(root, text="Select Bedrooms").pack()
bedroom_var = tk.IntVar(value=2)
tk.OptionMenu(root, bedroom_var, 1,2,3,4,5,6).pack()

# -------- Carpet Area (Range Slider) --------
tk.Label(root, text="Carpet Area (700 - 1500)").pack()
carpet_scale = tk.Scale(root, from_=700, to=1500, orient="horizontal")
carpet_scale.set(900)
carpet_scale.pack()

# -------- Price per sqft (Slider) --------
tk.Label(root, text="Price per Sqft (8000 - 10000)").pack()
sqft_scale = tk.Scale(root, from_=8000, to=10000, orient="horizontal")
sqft_scale.set(9000)
sqft_scale.pack()

# -------- Location (Names) --------
tk.Label(root, text="Select Location").pack()

locations = {
    "Chinchwad":0,
    "Moshi":1,
    "Punawale":2,
    "Ravet":3,
    "Tathawade":4,
    "Wakad":5
}

location_var = tk.StringVar()
location_var.set("Chinchwad")

tk.OptionMenu(root, location_var, *locations.keys()).pack()

# -------- Amenities --------
tk.Label(root, text="Select Amenities").pack()

amenities_vars = []
amenities_names = [
    "Spa", "Gym", "Kids Area",
    "Restaurant", "Palm Court", "Pet Park"
]

for name in amenities_names:
    var = tk.IntVar()
    tk.Checkbutton(root, text=name, variable=var).pack(anchor='w')
    amenities_vars.append(var)

# -------- Prediction --------
def predict_price():
    try:
        bedroom = bedroom_var.get()
        carpet_area = carpet_scale.get()
        per_sqft = sqft_scale.get()

        location_name = location_var.get()
        location = locations[location_name]

        amenity_feature = sum(var.get() for var in amenities_vars)

        prediction = model.predict([[bedroom, carpet_area, per_sqft, location, amenity_feature]])

        messagebox.showinfo("Result", f"Estimated Price: ₹ {int(prediction[0])}")

    except:
        messagebox.showerror("Error", "Invalid Input")

# -------- Button --------
tk.Button(root, text="Predict Price", command=predict_price,
          bg="green", fg="white", font=("Arial", 12)).pack(pady=20)

# Run
root.mainloop()

